---
 out_dir: '../results/'
 dataset_dir: "./dataset/pretrain_cleaned.smi"
 which_vocab: "selfies"
 vocab_path: "./vocab/pretrain_selfies_vocab.yaml"
 percentage: 1

 rnn_config:
  num_embeddings: 84
  embedding_dim: 256
  rnn_type: "GRU"


  input_size: 256
  hidden_size: 512
  num_layers: 3
  dropout: 0

 batch_size: 512
 shuffle: True
 num_epoch: 10
 which_optimizer: adam
 learning_rate: 0.001
 weight_decay: 0.0001